In [1]:
import pandas as pd

In [6]:
df1 = pd.read_json("../../data/pandas/example-1.json")
df2 = pd.read_json("../../data/pandas/example-2.json")
df_full = pd.concat([df1, df2])
df_full.reset_index()

   index  Column 1  Column 2
0      0         1         2
1      1         3         4
2      2         5         6
3      0         1         2
4      1         3         4
5      2         5         6

In [8]:
df_sales = pd.DataFrame(columns=['Date', 'Amount'])
df_sales

Empty DataFrame
Columns: [Date, Amount]
Index: []

In [11]:
new_data = {
    "Date": ["January 1", "January 2"],
    "Amount": [50000, 50000],
}
new_df_sales = pd.DataFrame(new_data)
new_df_sales

        Date  Amount
0  January 1   50000
1  January 2   50000

In [12]:
df_sales_full = pd.concat([df_sales, new_df_sales])
df_sales_full

        Date Amount
0  January 1  50000
1  January 2  50000

In [13]:
df_second = pd.DataFrame({"Date":["January 3","January 4" ], "Amount":[5600,5400]})
df_second

        Date  Amount
0  January 3    5600
1  January 4    5400

In [14]:
df_sls = pd.concat([df_sales_full, df_second])
df_sls

        Date Amount
0  January 1  50000
1  January 2  50000
0  January 3   5600
1  January 4   5400

In [16]:
df_sls.reset_index(drop=True, inplace=True)
df_sls

        Date Amount
0  January 1  50000
1  January 2  50000
2  January 3   5600
3  January 4   5400

In [17]:
df_one = pd.DataFrame(columns=['DOT', 'Branch Name', 'Amount','is Active'])
df_one

Empty DataFrame
Columns: [DOT, Branch Name, Amount, is Active]
Index: []

In [21]:
df_two = pd.DataFrame({
    'DOT': ["jan1" , "jan2", "jan3", "jan4"],
    'Branch Name' : ['Mumbai', 'Delhi', 'Chennai', 'Madras'],
    'Amount': [500,300,324,560],
    'is Active': [True, True, True, False]
})
df_two

    DOT Branch Name  Amount  is Active
0  jan1      Mumbai     500       True
1  jan2       Delhi     300       True
2  jan3     Chennai     324       True
3  jan4      Madras     560      False

In [22]:
df = pd.concat([df_one,df_two])
df.reset_index(inplace=True, drop=True)
df

    DOT Branch Name Amount is Active
0  jan1      Mumbai    500      True
1  jan2       Delhi    300      True
2  jan3     Chennai    324      True
3  jan4      Madras    560     False